
###

POST http://localhost:2940/api/v1/entities HTTP/1.1 
Content-Type: application/json

{
    "name": "Freddy Krueger",
    "age": 45,
    "tools": [
        {
            "name": "scissors"
        },
        {
            "name": "hat"
        }
    ]
}